Repository DDS-GmbH/jocument, pull requests merged in 2020-09, with the labels that each got.

#3 Closes #2 By Adding TemplateSource
  build.gradle
  src/main/java/com/docutools/jocument/Template.java
  src/main/java/com/docutools/jocument/TemplateSource.java
  src/main/java/com/docutools/jocument/impl/TemplateImpl.java
  src/main/java/com/docutools/jocument/impl/template/InMemoryTemplateSource.java
  src/main/java/com/docutools/jocument/impl/template/PathTemplateSource.java
  src/main/java/com/docutools/jocument/impl/template/URLTemplateSource.java
  src/test/java/com/docutools/jocument/TemplateLoading.java
  src/test/java/com/docutools/jocument/WordDocuments.java
Labels: enhancement

#5 Closes #4 Feature/allow transitive reflective access
  build.gradle
  src/main/java/com/docutools/jocument/impl/DocumentImpl.java
  src/main/java/com/docutools/jocument/impl/ReflectionResolver.java
  src/test/java/com/docutools/jocument/ReflectionResolving.java
  src/test/java/com/docutools/jocument/WordDocuments.java
  src/test/resources/templates/word/SETInTableTemplate.docx
Labels: enhancement

#13 Introduce owasp dependency-check
  build.gradle
Labels: operations

#18 Allow other Cells to be filled out in Collection Start/End Excel Row
  build.gradle
  src/main/java/com/docutools/jocument/impl/excel/implementations/ExcelGenerator.java
  src/main/java/com/docutools/jocument/impl/excel/util/ExcelUtils.java
Labels: enhancement

#14 Activate, configure checkstyle and bring jocument in line with the requirements
  .github/workflows/push.yml
  build.gradle
  config/checkstyle/checkstyle-supressions.xml
  config/checkstyle/checkstyle.xml
  config/checkstyle/suppressions.xml
  src/main/java/com/docutools/jocument/PlaceholderData.java
  src/main/java/com/docutools/jocument/PlaceholderResolver.java
  src/main/java/com/docutools/jocument/PlaceholderType.java
  src/main/java/com/docutools/jocument/Template.java
  src/main/java/com/docutools/jocument/TemplateSource.java
  src/main/java/com/docutools/jocument/annotations/Format.java
  src/main/java/com/docutools/jocument/annotations/Image.java
  src/main/java/com/docutools/jocument/annotations/Money.java
  src/main/java/com/docutools/jocument/annotations/Numeric.java
  src/main/java/com/docutools/jocument/annotations/Percentage.java
  src/main/java/com/docutools/jocument/impl/DocumentImpl.java
  src/main/java/com/docutools/jocument/impl/JsonResolver.java
  src/main/java/com/docutools/jocument/impl/ReflectionResolver.java
  src/main/java/com/docutools/jocument/impl/ReflectionUtils.java
  src/main/java/com/docutools/jocument/impl/TemplateImpl.java
  src/main/java/com/docutools/jocument/impl/excel/implementations/ExcelDocumentImpl.java
  src/main/java/com/docutools/jocument/impl/excel/implementations/ExcelGenerator.java
  src/main/java/com/docutools/jocument/impl/excel/implementations/SXSSFWriter.java
  src/main/java/com/docutools/jocument/impl/excel/interfaces/ExcelWriter.java
  src/main/java/com/docutools/jocument/impl/excel/util/ExcelUtils.java
  src/main/java/com/docutools/jocument/impl/template/InMemoryTemplateSource.java
  src/main/java/com/docutools/jocument/impl/template/PathTemplateSource.java
  src/main/java/com/docutools/jocument/impl/template/URLTemplateSource.java
  src/main/java/com/docutools/jocument/impl/word/WordDocumentImpl.java
  src/main/java/com/docutools/jocument/impl/word/WordGenerator.java
  src/main/java/com/docutools/jocument/impl/word/WordImageUtils.java
  src/main/java/com/docutools/jocument/impl/word/WordUtilities.java
  src/test/java/com/docutools/jocument/FormattingJsr310Values.java
  src/test/java/com/docutools/jocument/JsonResolving.java
  src/test/java/com/docutools/jocument/ParsingUtilsTest.java
  src/test/java/com/docutools/jocument/ReflectionResolving.java
  src/test/java/com/docutools/jocument/ReflectionUtilityTests.java
  src/test/java/com/docutools/jocument/ResolvingPlaceholder.java
  src/test/java/com/docutools/jocument/TestUtils.java
  src/test/java/com/docutools/jocument/WordDocuments.java
  src/test/java/com/docutools/jocument/excel/ExcelDocuments.java
  src/test/java/com/docutools/jocument/format/NumberFormatting.java
  src/test/java/com/docutools/jocument/localisation/DetectDocumentLanguage.java
  src/test/java/com/docutools/jocument/sample/SamplePlaceholderResolver.java
  src/test/java/com/docutools/jocument/sample/ServicePlaceholderResolver.java
  src/test/java/com/docutools/jocument/sample/model/Captain.java
  src/test/java/com/docutools/jocument/sample/model/City.java
  src/test/java/com/docutools/jocument/sample/model/PlanetServiceInfo.java
  src/test/java/com/docutools/jocument/sample/model/SampleModelData.java
  src/test/java/com/docutools/jocument/sample/model/Service.java
Labels: enhancement, operations

#21 Enable owasp dependency check
  .github/workflows/push.yml
  build.gradle
Labels: operations
